name: "Jekyll Configurations"
description: "Config file for jekyll"

url: "http://localhost:4000"

paginate: 5
paginate_path: "/blog/page:num/"

markdown: rdiscount
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
    
