name: "Get Mastered: Audio Experts"
description: "Collaborative, human mastering from experienced audio experts. Try our pro-bono mastering, free of charge."

fbphoto: getmastered.com/img/social-media/facebook-link-img.jpg


url: "http://getmastered.com"

gems:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num/"

# markdown: rdiscount
markdown: kramdown
permalink: /:categories/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
    
