name: "Jekyll Configurations"
description: "Config file for jekyll"

url: "http://localhost:4000"

# url: "http://getmastered.com"

gems:
  - jekyll-sitemap

paginate: 5
paginate_path: "/blog/page:num/"

# markdown: rdiscount
markdown: kramdown
permalink: /:categories/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
    
